[project]
name = "pytailwindcss"
version = "0.3.1"
description = "Standalone Tailwind CSS CLI, installable via pip. Use Tailwind CSS without Node.js."
authors = [{ name = "Tim Kamanin", email = "tim@timonweb.com" }]
readme = "README.md"
license = { text = "MIT" }
keywords = ["cli", "tailwind", "css"]
requires-python = ">=3.11"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries",
    "Topic :: Utilities",
    "Environment :: Web Environment"
]
dependencies = []

[project.urls]
Homepage = "https://github.com/timonweb/pytailwindcss"

[project.scripts]
tailwindcss = "pytailwindcss.__main__:main"
tailwindcss_install = "pytailwindcss.__main__:install"

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "pre-commit>=4.6.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/pytailwindcss"]
