name: pre-commit

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: '3.13'
      - run: uvx pre-commit run --all-files --show-diff-on-failure
